version: 2.1

orbs:
  node: circleci/node@5

jobs:
  build:
    executor: node/default
    steps:
      - checkout
      - node/install-packages:
          pkg-manager: npm
      - run:
          command: npm run build
      - run:
          name: Create the ~/artifacts directory if it doesn't exist
          command: mkdir -p ~/artifacts
      - run:
          name: Copy artifacts
          command: cp -R build dist public .output .next .docusaurus ~/artifacts 2>/dev/null || true
      - store_artifacts:
          path: ~/artifacts
          destination: node-build
  deploy:
    machine:
      image: ubuntu-2204:2023.07.2
    steps:
      - run:
          name: "echo an env var that is part of our project"
          command: |
            echo $SSH_USER
      - run:
          name: "echo an env var that is part of our project"
          command: |
            echo $SSH_HOST
      - run:
          name: "echo an env var that is part of our project"
          command: |
            echo $SSH_PORT
      - run:
          name: Deploy Over SSH
          command: |
            ssh $SSH_USER@$SSH_HOST -p $SSH_PORT "touch ~/test.txt"

workflows:
  build-and-deploy:
    jobs:
      - build
      - deploy:
          requires:
            - build
          # filters:
          #   branches:
          #     only: main
